[package]
name = "rnd_name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for random number
rand = "0.8.5"
async-std = "1.12.0"
futures = { version = "0.3", features = [] }
log = "0.4.21"